"""fixing errors

Revision ID: 030da8297321
Revises: 399ef027b060
Create Date: 2025-09-23 16:27:11.335105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030da8297321'
down_revision = '399ef027b060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
