"""added quantity to order

Revision ID: 81928599767f
Revises: b758ffe147c1
Create Date: 2025-09-25 15:11:59.913689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81928599767f'
down_revision = 'b758ffe147c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
